name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: [ "bug" ]

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue clearly.
      placeholder: What did you observe?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Describe expected result
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 1.0.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Errors
      description: Paste any relevant logs or errors
      render: shell
    validations:
      required: false
